security:
    # Configuration des encodages de mot de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Configuration des fournisseurs d'utilisateurs
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Définition des pare-feu (firewalls)
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login  # Route pour afficher la page de connexion
                check_path: app_login  # Route pour traiter le formulaire de connexion
                enable_csrf: true
                default_target_path: /home
            logout:
                path: app_logout  # Route pour la déconnexion
                # where to redirect after logout
                target: app_home
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 semaine
                path: /
    
    # Définition des rôles et restrictions d'accès
    access_control:
        - { path: ^/home, roles: PUBLIC_ACCESS }  # Permet à tout le monde d'accéder à /home
        - { path: ^/admin, roles: ROLE_ADMIN }  # Restriction aux admins pour /admin
        - { path: ^/profile, roles: ROLE_USER }  # Accessible aux utilisateurs connectés
        - { path: ^/back, roles: ROLE_ADMIN }  # Restreint l'accès aux pages utilisateur

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
